export type FormData = {
    data: any
    checkInTime: string
    checkOutTime: string
    selfCheckIn: boolean
    luggageCheckIn: boolean
    luggageDropTime: string
    rentalLicense: boolean
    extraLicenseRequired: boolean
    extraLicenceGMAG: boolean
    extraEcoHouse:boolean
    extraPartiesNotAllowed: boolean
    extraPartiesAllowed: boolean
    wheelchairFriendly: boolean
    childrenAllowed: boolean
    petsAllowed: boolean
    smokingAllowed: boolean
    villa: boolean
    apartment: boolean
    maissonette: boolean
    room: boolean
    studio: boolean
    cottage: boolean
    bangalow: boolean
    house: boolean
    awayFromItAll: boolean
    livingRoomOnePerLevel: boolean
    family: boolean
    romantic: boolean
    historical: boolean
    traditionalProperty: boolean
    secluded: boolean
    brandNew: boolean
    detached: boolean
    semiDetached: boolean
    privateResidence: boolean
    kitchenGround: boolean
    dinerGround: boolean
    numOfFloorsToGround: string
    areaOfTheHouseInM2: string
    surroundingAreaInM2: string
    yearOfBuilt: string
    serviceSupermarket: boolean
    singleLevelHome: boolean
    serviceBoatTaxiService: boolean
    serviceLunch: boolean
    serviceOwnerNearby: boolean
    serviceMealDeliveryService: boolean
    childrenYes: boolean
    garden: boolean
    viewOcean: boolean
    resort: boolean
    river: boolean
    rural: boolean
    skiIn: boolean
    skiOut: boolean
    town: boolean
    village: boolean
    waterView: boolean
    waterfront: boolean
    viewSea: boolean
    viewSunset: boolean
    viewPanoramic: boolean
    viewSunrise: boolean
    viewCountryside: boolean
    viewBayView: boolean
    viewBeachView: boolean
    viewCityView: boolean
    viewGardenView: boolean
    viewHarborView: boolean
    viewMarinaView: boolean
    viewMountainView: boolean
    viewPoolView: boolean
    viewResortView: boolean
    viewValleyView: boolean
    viewVineyardView: boolean
    onTheBeach: boolean
    walkToTheBeach: boolean
    highway: boolean
    ski: boolean
    train: boolean
    taverna: boolean
    countryside: boolean
    beachFront: boolean
    closestBeach: string
    distanceToTheBeach: string
    distanceToCityCenter: string
    distanceToShops: string
    distanceToAirport: string
    distanceToKiosk: string
    distanceToBar: string
    distanceToFerry: string
    distanceToGolf: string
    nearestVillage: string
    nearestRestaurant: string
    nearestSupermarket: string
    nearestMiniMarket: string
    nearestPointOfInterest: string
    nearestAtm: string
    nearestBank: string
    nearestWaterPark: string
    nearestMarina: string
    nearestDiveCenter: string
    nearestHospital: string
    nearestPoliceStation: string
    nearestPetrolStation: string
    nearestBusStation: string
    nearestTennisCourt: string
    nearestPharmacy: string
    nearestHairdressers: string
    nearestMedicalCenter: string
    nearestLaunderette: string
    propertyAddress: string
    postCode: string
    gpsLatitude: string
    gpsLongitude: string
    basketballCourt: boolean
    cycling: boolean
    crossCountrySkiing: boolean
    deepseaFishing: boolean
    equestrianEvents: boolean
    fishing: boolean
    fishingBay: boolean
    fishingFly: boolean
    fishingFreshwater: boolean
    fishingSurf: boolean
    golf: boolean
    golfOptional: boolean
    hiking: boolean
    hotAirBallooning: boolean
    hunting: boolean
    area: boolean
    sports: boolean
    iceSkating: boolean
    jetSkiing: boolean
    kayaking: boolean
    mountainBiking: boolean
    mountainClimbing: boolean
    mountaineering: boolean
    paragliding: boolean
    parasailing: boolean
    pierFishing: boolean
    rafting: boolean
    racquetball: boolean
    rockClimbing: boolean
    rollerBlading: boolean
    sailing: boolean
    skiLiftPrivileges: boolean
    skiLiftPrivilegesOptional: boolean
    skiing: boolean
    skiingWater: boolean
    snorkeling: boolean
    snowboarding: boolean
    snowmobiling: boolean
    spelunking: boolean
    surfing: boolean
    swimming: boolean
    tennis: boolean
    whitewaterRafting: boolean
    windSurfing: boolean
    sportsSnorkelingDiving: boolean
    sportsTubingWater: boolean
    powerBoatRental: boolean
    scubaOrSnorkeling: string
    attractionBay: boolean
    attractionAttractionscoinLaundry: boolean
    attractionDutyFree: boolean
    attractionHealthBeautyspa: boolean
    attractionMarina: boolean
    attractionMuseums: boolean
    attractionThemeParks: boolean
    attractionWaterParks: boolean
    attractionWineryTours: boolean
    attractionZoo: boolean
    leisureAntiquing: boolean
    leisureBirdWatching: boolean
    leisureEcoTourism: boolean
    leisureGambling: boolean
    leisureHorsebackRiding: boolean
    leisureOutletShopping: boolean
    leisurePaddleBoating: boolean
    leisureSledding: boolean
    leisureBoating: boolean
    leisureShopping: boolean
    leisureWildLifeViewing: boolean
    leisureWaterSports: boolean
    leisureFitnessCenter: boolean
    leisureHospital: boolean
    leisureLaundromat: boolean
    levelGround: boolean
    terrace: boolean
    outsideFurniture: boolean
    depthMarks: boolean
    safetySign: boolean
    swimmingRing: boolean
    staircase: boolean
    jacuzziJets: boolean
    poolMaintenace: boolean
    accessToPool: boolean
    fence: boolean
    poolTowels: boolean
    poolShower: boolean
    poolLasso: boolean
    solarPanels: boolean
    inflatables: boolean
    minWidth: string
    maxWidth: string
    minDepth: string
    maxdepth: string
}