export type FormDataTypes = {
    
    checkInTime: string
    checkOutTime: string
    selfCheckIn: boolean
    luggageCheckIn: boolean
    luggageDropTime: string
    rentalLicense: boolean
    extraLicenseRequired: boolean
    extraLicenceGMAG: boolean
    extraEcoHouse:boolean
    extraPartiesNotAllowed: boolean
    extraPartiesAllowed: boolean
    wheelchairFriendly: boolean
    childrenAllowed: boolean
    petsAllowed: boolean
    smokingAllowed: boolean
    lodgingType: string
    awayFromItAll: boolean
    livingRoom: boolean
    livingRoomDescription: string
    family: boolean
    romantic: boolean
    historical: boolean
    traditionalProperty: boolean
    secluded: boolean
    brandNew: boolean
    detached: boolean
    semiDetached: boolean
    privateResidence: boolean
    kitchenGround: boolean
    diner: boolean
    dinerDescription: string
    numOfFloorsToGround: string
    areaOfTheHouseInM2: string
    surroundingAreaInM2: string
    yearOfBuilt: string
    serviceSupermarket: boolean
    serviceSupermarketDelivery: boolean
    singleLevelHome: boolean
    serviceBoatTaxiService: boolean
    serviceLunch: boolean
    serviceOwnerNearby: boolean
    serviceMealDeliveryService: boolean
    childrenYes: boolean
    garden: boolean
    viewOcean: boolean
    resort: boolean
    river: boolean
    rural: boolean
    skiIn: boolean
    skiOut: boolean
    town: boolean
    village: boolean
    waterView: boolean
    waterfront: boolean
    viewSea: boolean
    viewSunset: boolean
    viewPanoramic: boolean
    viewSunrise: boolean
    viewCountryside: boolean
    viewBayView: boolean
    viewBeachView: boolean
    viewCityView: boolean
    viewGardenView: boolean
    viewHarborView: boolean
    viewMarinaView: boolean
    viewMountainView: boolean
    viewPoolView: boolean
    viewResortView: boolean
    viewValleyView: boolean
    viewVineyardView: boolean
    onTheBeach: boolean
    walkToTheBeach: boolean
    highway: boolean
    ski: boolean
    train: boolean
    taverna: boolean
    countryside: boolean
    beachFront: boolean
    closestBeach: string
    distanceToTheBeach: string
    distanceToCityCenter: string
    distanceToShops: string
    distanceToAirport: string
    distanceToKiosk: string
    distanceToBar: string
    distanceToFerry: string
    distanceToGolf: string
    nearestVillage: string
    nearestRestaurant: string
    nearestSupermarket: string
    nearestMiniMarket: string
    nearestPointOfInterest: string
    nearestAtm: string
    nearestBank: string
    nearestWaterPark: string
    nearestMarina: string
    nearestDiveCenter: string
    nearestHospital: string
    nearestPoliceStation: string
    nearestPetrolStation: string
    nearestBusStation: string
    nearestTennisCourt: string
    nearestPharmacy: string
    nearestHairdressers: string
    nearestMedicalCenter: string
    nearestLaunderette: string
    propertyAddress: string
    postCode: string
    gpsLatitude: string
    gpsLongitude: string
    cycling: boolean
    crossCountrySkiing: boolean
    deepseaFishing: boolean
    equestrianEvents: boolean
    fishing: boolean
    fishingBay: boolean
    fishingFly: boolean
    fishingFreshwater: boolean
    fishingSurf: boolean
    golf: boolean
    golfOptional: boolean
    hiking: boolean
    hotAirBallooning: boolean
    hunting: boolean
    area: boolean
    sports: boolean
    iceSkating: boolean
    jetSkiing: boolean
    kayaking: boolean
    mountainBiking: boolean
    mountainClimbing: boolean
    mountaineering: boolean
    paragliding: boolean
    parasailing: boolean
    pierFishing: boolean
    rafting: boolean
    racquetball: boolean
    rockClimbing: boolean
    rollerBlading: boolean
    sailing: boolean
    skiLiftPrivileges: boolean
    skiLiftPrivilegesOptional: boolean
    skiing: boolean
    skiingWater: boolean
    snorkeling: boolean
    snowboarding: boolean
    snowmobiling: boolean
    spelunking: boolean
    surfing: boolean
    swimming: boolean
    tennis: boolean
    whitewaterRafting: boolean
    windSurfing: boolean
    sportsSnorkelingDiving: boolean
    sportsTubingWater: boolean
    powerBoatRental: boolean
    scubaOrSnorkeling: string
    attractionBay: string
    attractionAttractionscoinLaundry: string
    attractionDutyFree: string
    attractionHealthBeautyspa: string
    attractionMarina: string
    attractionMuseums: string
    attractionThemeParks: string
    attractionWaterParks: string
    attractionWineryTours: string
    attractionZoo: string
    leisureAntiquing: string
    leisureBirdWatching: string
    leisureEcoTourism: string
    leisureGambling: string
    leisureHorsebackRiding: string
    leisureOutletShopping: string
    leisurePaddleBoating: string
    leisureSledding: string
    leisureBoating: string
    leisureShopping: string
    leisureWildLifeViewing: string
    leisureWaterSports: string
    leisureFitnessCenter: string
    leisureHospital: string
    leisureLaundromat: string
    levelGround: boolean
    terrace: boolean
    outsideFurniture: boolean
    depthMarks: boolean
    safetySign: boolean
    swimmingRing: boolean
    staircase: boolean
    jacuzziJets: boolean
    poolMaintenace: boolean
    accessToPool: boolean
    fence: boolean
    poolTowels: boolean
    poolShower: boolean
    poolLasso: boolean
    solarPanels: boolean
    inflatables: boolean
    minWidth: string
    maxWidth: string
    minDepth: string
    maxdepth: string
    garage: boolean
    outsideTableTennis: boolean
    insideTableTennis: boolean
    tennisCourt: boolean
    balcony: boolean
    poolTable: boolean
    diningTerrace: boolean
    yard: boolean
    freeParkingOnTheStreet: boolean
    privateParking: boolean
    chairsAndTableOutside: boolean
    grass: boolean
    trees: boolean
    gardener: boolean
    waterFromAPersonalSupply: boolean
    outdoorJacuzzi: boolean
    footballGame: boolean
    roofTerrace: boolean
    outsideKitchen: boolean
    traditionalPizzaOven: boolean
    outsideFridge: boolean
    extraWaterTank: boolean
    playground: boolean
    hammock: boolean
    gardenSwing: boolean
    washingBasin: boolean
    deck: boolean
    outdoorDining: boolean
    porch: boolean
    insideMiniBar: boolean
    outsideMiniBar: boolean
    basketballCourt: boolean
    drinkingWater: boolean
    poofPilows: boolean
    parkingAvailable: string
    terraceOrVeranda: string
    shadedTerraceOrveranda: string
    barbeque: string
    umbrella: string
    sunloungers: string
    kioskWithDiningFacilities: string
    fireplaceType: string
    heatingMeans: string
    tvType: string
    hydroMassageType: string
    internetType: string
    heating: boolean
    acInLounge: boolean
    sofa: boolean
    musicSystem: boolean
    ironNIroningBoard: boolean
    dvdPlayer: boolean
    dishwasher: boolean
    washingMachine: boolean
    hairdryer: boolean
    airConditioning: boolean
    ceilingFans: boolean
    gym: boolean
    cleaningMaterials: boolean
    availableSmallGames: boolean
    books: boolean
    tumbleDryer: boolean
    electricityKeyFob: boolean
    laundryRoom: boolean
    clothesDryerRack: boolean
    fan: boolean
    entertainmentVideogames: boolean
    amenitieswoodStove: boolean
    amenitiesFitnessRoom: boolean
    entertainmentSatelliteOrCable: boolean
    entertainmentVideoLibrary: boolean
    amenitiesElevator: boolean
    entertainmentToys: boolean
    amenitiesTelephone: boolean
    amenitiesGameRoom: boolean
    entertainmentMusicLibrary: boolean
    clothesStorage: boolean
    privateEntrance: boolean
    washerDryer: boolean
    safeBox: boolean
    insideJacuzzi: boolean
    snookerTable: boolean
    hotWaterFromElectric: boolean
    hotWaterFromSolar: boolean
    sauna: boolean
    petrolBoiler: boolean
    workStation: boolean
    mosquitoNet: boolean
    outletAdapters: boolean
    networkCode: boolean
    wifiBroadband: boolean
    freeWifi: boolean
    coffeeTypeAvailable:string
    cookerWithFullOven: string
    fridgeOrFreezer: string
    microwave: boolean
    toaster: boolean
    cookerWithSmallOven: boolean
    smallFridge: boolean
    dinningArea: boolean
    dishesAndSilverware: boolean
    kitchen: boolean
    dinningRoomOrSpace: boolean
    highChair: boolean
    waterDispenser: boolean
    cookingBasics: boolean
    diningTable: boolean
    cookwareAndKitchenUtensils: boolean
    separateStove: boolean
    wineGlasses: boolean
    kettle: boolean
    sandwichToaster: boolean
    espressoCoffeeMachine: boolean
    stove: boolean
    blenderOrMulti: boolean
    filterCoffeeMachine: boolean
    kitchenette: boolean
    fryer: boolean
    mixer: boolean
    extraSmallBbqOven: boolean
    breadMaker: boolean
    carbonMonoxideAlarm: boolean
    emergencyExitRoute: boolean
    fireEmergencyContact: boolean
    fireExtinguisher: boolean
    firstAidKit: boolean
    medicalEmergencyContact: boolean
    policeEmergencyContact: boolean
    smokeAlarm: boolean
    deadboltLock: boolean
    outdoorLighting: boolean
    lightningProtection: boolean
    bedroomOneType: string
    bedroomTwoType: string
    bedroomThreeType: string
    bedroomFourType: string
    bedroomFiveType: string
    bedroomSixType: string
    bedroomSevenType: string
    bathroomOne: string
    bathroomTwo: string
    bathroomThree: string
    bathroomFour: string
    bathroomFive: string
    bathroomSix: string
    bathroomSeven: string
    bedroomOneHeating: string
    bedroomTwoHeating: string
    bedroomThreeHeating: string
    bedroomFourHeating: string
    bedroomFiveHeating: string
    bedroomSixHeating: string
    bedroomSevenHeating: string
    bathroomsCommonOne: string
    bathroomsCommonTwo: string
    bathroomsCommonThree: string
    bathroomsCommonFour: string
    bathroomsCommonFive: string
    bathroomsCommonSix: string
    bathroomsCommonSeven: string
    commonAreaBedOne: string
    commonAreaBedTwo: string
    cot: string
    enSuiteBathroomOne: string
    extrasBabyBath: boolean
    extrasBabyPotty: boolean
    extrasChangingMat: boolean
    extrasBabyLinen: boolean
    extrasBabyWashingGel: boolean
    extrasPortBebe: boolean
    extrasBabyListeningDevice: boolean
    extrasBabyChangingTable: boolean
    extrasChildSafetyGate: boolean
    cleaningProducts: boolean
    beachSunLoungersProvided: boolean
    beachTowelsCoolBagsAndBoxes: boolean
    beachTowelsProvided: boolean
    essentials: boolean
    hangers: boolean
    extraPillowsAndBlankets: boolean
    roomDarkeningShades: boolean
    showerGel: boolean
    extrasBeachChair: boolean
    extrasPaddleBoard: boolean
    hotWaterProvided: boolean
    maidEveryDay: boolean
    maidOnceAWeek: boolean
    maidTwiceAWeek: boolean
    maidThriceAWeek: boolean
    bedLinen: boolean
    linenOnceAWeek: boolean
    linenTwiceAWeek: boolean
    towels: boolean
    towelsOnceAWeek: boolean
    towelsTwiceAWeek: boolean
    towelsThriceAWeek: boolean
    shampooProvided: boolean
    maidBreakfastIncluded: boolean
    carHireRecommended: boolean
    carHireNotEssential: boolean
    extraKeyLocation: string
    keyLocation: string
    linenCleaningMethod: string
    safeEnhachedCleaning: string
    safeCleaningDisinfection: string
    safeSelfCheckInCheckOut: string
    safeCommonSurfaceDisinfecting: string
    safeSanitaryAssociation: string
    sanitaryStandard: string
    physicalDistancing: boolean
    briefDescription: string
    
    data: any
    setData: any
    handleFieldChange: any
    handleValueChange: string
    updateFields: (fields: Partial<FormDataTypes>) => void
}