import { FormDataTypes } from "@/app/types/all-form-types"

const INITIAL_DATA: FormDataTypes = {
  poolYesNo: false,
  checkInTime: "15:00",
  checkOutTime: "10:00",
  selfCheckIn: false,
  luggageCheckIn: false,
  luggageDropTime: "",
  rentalLicense: false,
  extraLicenseRequired: false,
  extraLicenseType: "",
  extraEcoHouse: false,
  extraPartiesNotAllowed: false,
  extraPartiesAllowed: false,
  wheelchairFriendly: false,
  childrenAllowed: false,
  petsAllowed: false,
  smokingAllowed: false,
  lodgingType: "villa",
  awayFromItAll: false,
  livingRoom: false,
  livingRoomDescription: "",
  family: false,
  romantic: false,
  historical: false,
  traditionalProperty: false,
  secluded: false,
  brandNew: false,
  detached: false,
  semiDetached: false,
  privateResidence: false,
  kitchenGround: false,
  diner: false,
  dinerDescription: "",
  numOfFloorsToGround: "",
  areaOfTheHouseInM2: "",
  surroundingAreaInM2: "",
  yearOfBuilt: "",
  serviceSupermarket: false,
  singleLevelHome: false,
  serviceBoatTaxiService: false,
  serviceLunch: false,
  serviceOwnerNearby: false,
  serviceMealDeliveryService: false,
  childrenYes: false,
  garden: false,
  viewOcean: false,
  resort: false,
  river: false,
  rural: false,
  skiIn: false,
  skiOut: false,
  town: false,
  village: false,
  waterView: false,
  waterfront: false,
  viewSea: false,
  viewSunset: false,
  viewPanoramic: false,
  viewSunrise: false,
  viewCountryside: false,
  viewBayView: false,
  viewBeachView: false,
  viewCityView: false,
  viewGardenView: false,
  viewHarborView: false,
  viewMarinaView: false,
  viewMountainView: false,
  viewPoolView: false,
  viewResortView: false,
  viewValleyView: false,
  viewVineyardView: false,
  nearestVillage: "",
  onTheBeach: false,
  walkToTheBeach: false,
  distanceToCityCenter: "",
  taverna: false,
  distanceToTheBeach: "",
  countryside: false,
  beachFront: false,
  distanceToShops: "",
  distanceToAirport: "",
  distanceToKiosk: "",
  distanceToBar: "",
  distanceToFerry: "",
  distanceToGolf: "",
  highway: false,
  ski: false,
  train: false,
  closestBeach: "",
  nearestRestaurant: "",
  nearestSupermarket: "",
  nearestMiniMarket: "",
  nearestPointOfInterest: "",
  nearestAtm: "",
  nearestBank: "",
  nearestWaterPark: "",
  nearestMarina: "",
  nearestDiveCenter: "",
  nearestHospital: "",
  nearestPoliceStation: "",
  nearestPetrolStation: "",
  nearestBusStation: "",
  nearestTennisCourt: "",
  nearestPharmacy: "",
  nearestHairdressers: "",
  nearestMedicalCenter: "",
  nearestLaunderette: "",
  propertyAddress: "",
  postCode: "",
  gpsLatitude: "",
  gpsLongitude: "",
  basketballCourt: false,
  cycling: false,
  crossCountrySkiing: false,
  deepseaFishing: false,
  equestrianEvents: false,
  fishing: false,
  fishingBay: false,
  fishingFly: false,
  fishingFreshwater: false,
  fishingSurf: false,
  golf: false,
  golfOptional: false,
  hiking: false,
  hotAirBallooning: false,
  hunting: false,
  area: false,
  sports: false,
  iceSkating: false,
  jetSkiing: false,
  kayaking: false,
  mountainBiking: false,
  mountainClimbing: false,
  mountaineering: false,
  paragliding: false,
  parasailing: false,
  pierFishing: false,
  rafting: false,
  racquetball: false,
  rockClimbing: false,
  rollerBlading: false,
  sailing: false,
  skiLiftPrivileges: false,
  skiLiftPrivilegesOptional: false,
  skiing: false,
  skiingWater: false,
  snorkeling: false,
  snowboarding: false,
  snowmobiling: false,
  spelunking: false,
  surfing: false,
  swimming: false,
  tennis: false,
  whitewaterRafting: false,
  windSurfing: false,
  sportsSnorkelingDiving: false,
  sportsTubingWater: false,
  powerBoatRental: false,
  scubaOrSnorkeling: "",
  attractionBay: "",
  attractionAttractionscoinLaundry: "",
  attractionDutyFree: "",
  attractionHealthBeautyspa: "",
  attractionMarina: "",
  attractionMuseums: "",
  attractionThemeParks: "",
  attractionWaterParks: "",
  attractionWineryTours: "",
  attractionZoo: "",
  leisureAntiquing: "",
  leisureBirdWatching: "",
  leisureEcoTourism: "",
  leisureGambling: "",
  leisureHorsebackRiding: "",
  leisureOutletShopping: "",
  leisurePaddleBoating: "",
  leisureSledding: "",
  leisureBoating: "",
  leisureShopping: "",
  leisureWildLifeViewing: "",
  leisureWaterSports: "",
  leisureFitnessCenter: "",
  leisureHospital: "",
  leisureLaundromat: "",
  poolLevel: "",
  terrace: false,
  poolFurniture: false,
  depthMarks: false,
  safetySign: false,
  poolRing: false,
  staircase: false,
  jacuzziJets: false,
  poolMaintained: false,
  accessToPool: false,
  fence: false,
  poolTowels: false,
  poolShower: false,
  poolLasso: false,
  solarPanels: false,
  inflatables: false,
  minWidth: "",
  maxWidth: "",
  minDepth: "",
  maxdepth: "",
  garage: false,
  outsideTableTennis: false,
  insideTableTennis: false,
  tennisCourt: false,
  balcony: false,
  poolTable: false,
  diningTerrace: false,
  yard: false,
  freeParkingOnTheStreet: false,
  privateParking: false,
  chairsAndTableOutside: false,
  grass: false,
  trees: false,
  gardener: false,
  waterFromAPersonalSupply: false,
  outdoorJacuzzi: false,
  footballGame: false,
  roofTerrace: false,
  outsideKitchen: false,
  traditionalPizzaOven: false,
  outsideFridge: false,
  extraWaterTank: false,
  playground: false,
  hammock: false,
  gardenSwing: false,
  washingBasin: false,
  deck: false,
  outdoorDining: false,
  porch: false,
  insideMiniBar: false,
  outsideMiniBar: false,
  drinkingWater: false,
  poofPilows: false,
  parkingAvailable: false,
  parkingDescription: "",
  terraceOrVeranda: "",
  shadedTerraceOrveranda: "",
  barbeque: "",
  umbrella: "",
  sunloungers: "",
  kioskWithDiningFacilities: "",
  fireplaceType: "",
  tvType: "",
  hydroMassageType: "",
  internetType: "",
  heating: "",
  acInLounge: false,
  sofa: false,
  musicSystem: false,
  ironNIroningBoard: false,
  dvdPlayer: false,
  dishwasher: false,
  washingMachine: false,
  hairdryer: false,
  airConditioningCooling: false,
  airConditioningHeating: false,
  ceilingFans: false,
  standingFans: false,
  gym: false,
  cleaningMaterials: false,
  availableSmallGames: false,
  books: false,
  tumbleDryer: false,
  electricityKeyFob: false,
  laundryRoom: false,
  clothesDryerRack: false,
  fan: false,
  videoGames: false,
  woodStove: false,
  fitnessRoom: false,
  satelliteOrCable: false,
  videoLibrary: false,
  elevator: false,
  toys: false,
  telephone: false,
  gameRoom: false,
  musicLibrary: false,
  clothesStorage: false,
  privateEntrance: false,
  washerDryer: false,
  safeBox: false,
  insideJacuzzi: false,
  snookerTable: false,
  hotWaterFromElectric: false,
  hotWaterFromSolar: false,
  sauna: false,
  petrolBoiler: false,
  workStation: false,
  mosquitoNets: false,
  outletAdapters: false,
  networkCode: false,
  wifiBroadband: false,
  freeWifi: false,
  coffeeTypeAvailable: "",
  cookerWithFullOven: "",
  fridgeOrFreezer: "",
  microwave: false,
  toaster: false,
  cookerWithSmallOven: false,
  smallFridge: false,
  dinningArea: false,
  dishesAndSilverware: false,
  kitchen: false,
  dinningRoomOrSpace: false,
  highChair: false,
  waterDispenser: false,
  cookingBasics: false,
  diningTable: false,
  cookwareAndKitchenUtensils: false,
  separateStove: false,
  wineGlasses: false,
  kettle: false,
  sandwichToaster: false,
  espressoCoffeeMachine: false,
  stove: false,
  blenderOrMulti: false,
  filterCoffeeMachine: false,
  kitchenette: false,
  fryer: false,
  mixer: false,
  extraSmallBbqOven: false,
  breadMaker: false,
  carbonMonoxideAlarm: false,
  emergencyExitRoute: false,
  fireEmergencyContact: false,
  fireExtinguisher: false,
  firstAidKit: false,
  medicalEmergencyContact: false,
  policeEmergencyContact: false,
  smokeAlarm: false,
  deadboltLock: false,
  outdoorLighting: false,
  lightningProtection: false,
  bedroomNumber: 0,
  bedrooms: [],
  bathroomNumber: 1,
  sofaBedsNumber: 0,
  campBedsNumber: 0,
  foldingBedsNumber: 0,
  cotsNumber: 0,
  enSuiteBathsNumber: 0,
  commonBathsNumber: 0,
  maxPaxNumber: 1,
  maxAdultsNumber: 1,
  maxChildrenNumber: 1,
  bedroomOne: "",
  // bedroomOneBedNum: 1,
  // bedroomOneLevel: "",
  // bedroomOneBeds1: "",
  // bedroomOneBeds2: "",
  // bedroomOneBeds3: "",
  // bedroomOneBeds4: "",
  // bedroomOneBeds5: "",
  // bedroomOneBeds6: "",
  // bedroomOneBeds7: "",
  bedroomTwo: "",
  // bedroomTwoBedNum: 1,
  // bedroomTwoLevel: "",
  // bedroomTwoBeds1: "",
  // bedroomTwoBeds2: "",
  // bedroomTwoBeds3: "",
  // bedroomTwoBeds4: "",
  // bedroomTwoBeds5: "",
  // bedroomTwoBeds6: "",
  // bedroomTwoBeds7: "",
  bedroomThree: "",
  // bedroomThreeBedNum: 1,
  // bedroomThreeLevel: "",
  // bedroomThreeBeds1: "",
  // bedroomThreeBeds2: "",
  // bedroomThreeBeds3: "",
  // bedroomThreeBeds4: "",
  // bedroomThreeBeds5: "",
  // bedroomThreeBeds6: "",
  // bedroomThreeBeds7: "",
  bedroomFour: "",
  // bedroomFourBedNum: 1,
  // bedroomFourLevel: "",
  // bedroomFourBeds1: "",
  // bedroomFourBeds2: "",
  // bedroomFourBeds3: "",
  // bedroomFourBeds4: "",
  // bedroomFourBeds5: "",
  // bedroomFourBeds6: "",
  // bedroomFourBeds7: "",
  bedroomFive: "",
  // bedroomFiveBedNum: 1,
  // bedroomFiveLevel: "",
  // bedroomFiveBeds1: "",
  // bedroomFiveBeds2: "",
  // bedroomFiveBeds3: "",
  // bedroomFiveBeds4: "",
  // bedroomFiveBeds5: "",
  // bedroomFiveBeds6: "",
  // bedroomFiveBeds7: "",
  bedroomSix: "",
  // bedroomSixBedNum: 1,
  // bedroomSixLevel: "",
  // bedroomSixBeds1: "",
  // bedroomSixBeds2: "",
  // bedroomSixBeds3: "",
  // bedroomSixBeds4: "",
  // bedroomSixBeds5: "",
  // bedroomSixBeds6: "",
  // bedroomSixBeds7: "",
  bedroomSeven: "",
  // bedroomSevenBedNum: 1,
  // bedroomSevenLevel: "",
  // bedroomSevenBeds1: "",
  // bedroomSevenBeds2: "",
  // bedroomSevenBeds3: "",
  // bedroomSevenBeds4: "",
  // bedroomSevenBeds5: "",
  // bedroomSevenBeds6: "",
  // bedroomSevenBeds7: "",
  bedroomEight: "",
  // bedroomEightBedNum: 1,
  // bedroomEightLevel: "",
  // bedroomEightBeds1: "",
  // bedroomEightBeds2: "",
  // bedroomEightBeds3: "",
  // bedroomEightBeds4: "",
  // bedroomEightBeds5: "",
  // bedroomEightBeds6: "",
  // bedroomEightBeds7: "",
  bedroomNine: "",
  // bedroomNineBedNum: 1,
  // bedroomNineLevel: "",
  // bedroomNineBeds1: "",
  // bedroomNineBeds2: "",
  // bedroomNineBeds3: "",
  // bedroomNineBeds4: "",
  // bedroomNineBeds5: "",
  // bedroomNineBeds6: "",
  // bedroomNineBeds7: "",
  bedroomTen: "",
  // bedroomTenBedNum: 1,
  // bedroomTenLevel: "",
  // bedroomTenBeds1: "",
  // bedroomTenBeds2: "",
  // bedroomTenBeds3: "",
  // bedroomTenBeds4: "",
  // bedroomTenBeds5: "",
  // bedroomTenBeds6: "",
  // bedroomTenBeds7: "",
  bathroomOne: "",
  bathroomTwo: "",
  bathroomThree: "",
  bathroomFour: "",
  bathroomFive: "",
  bathroomSix: "",
  bathroomSeven: "",
  bathroomEight: "",
  bathroomNine: "",
  bathroomTen: "",
  bedroomOneHeating: "",
  bedroomTwoHeating: "",
  bedroomThreeHeating: "",
  bedroomFourHeating: "",
  bedroomFiveHeating: "",
  bedroomSixHeating: "",
  bedroomSevenHeating: "",
  bathroomsCommonOne: "",
  bathroomsCommonTwo: "",
  bathroomsCommonThree: "",
  bathroomsCommonFour: "",
  bathroomsCommonFive: "",
  bathroomsCommonSix: "",
  bathroomsCommonSeven: "",
  commonAreaBedOne: "",
  commonAreaBedTwo: "",
  enSuiteBathroomOne: "",
  extrasBabyBath: false,
  extrasBabyPotty: false,
  extrasChangingMat: false,
  extrasBabyLinen: false,
  extrasBabyWashingGel: false,
  extrasPortBebe: false,
  extrasBabyListeningDevice: false,
  extrasBabyChangingTable: false,
  extrasChildSafetyGate: false,
  cleaningProducts: false,
  beachSunLoungersProvided: false,
  beachTowelsCoolBagsAndBoxes: false,
  beachTowelsProvided: false,
  essentials: false,
  hangers: false,
  extraPillowsAndBlankets: false,
  roomDarkeningShades: false,
  showerGel: false,
  extrasBeachChair: false,
  extrasPaddleBoard: false,
  hotWaterProvided: false,
  maidEveryDay: false,
  maidOnceAWeek: false,
  maidTwiceAWeek: false,
  maidThriceAWeek: false,
  bedLinen: false,
  linenOnceAWeek: false,
  linenTwiceAWeek: false,
  towels: false,
  towelsOnceAWeek: false,
  towelsTwiceAWeek: false,
  towelsThriceAWeek: false,
  shampooProvided: false,
  maidBreakfastIncluded: false,
  carHireRecommended: false,
  carHireNotEssential: false,
  extraKeyLocation: "",
  keyLocation: "",
  linenCleaningMethod: "",
  safeEnhachedCleaning: "",
  safeCleaningDisinfection: "",
  safeSelfCheckInCheckOut: "",
  safeCommonSurfaceDisinfecting: "",
  safeSanitaryAssociation: "",
  sanitaryStandard: "",
  physicalDistancing: false,
  briefDescription: "",
  serviceSupermarketDelivery: false,





 









}


export default INITIAL_DATA;





